insert into books (id, name, image, supplier, author, translator, publisher, publish_year, weight, demension, pages, cover, price, stock, details, book_type, is_delete) values (1, 'Lời tự thú của 1 bậc thầy quảng cáo ', 'https://firebasestorage.googleapis.com/v0/b/sprint-2-data.appspot.com/o/sach_kinh_te%2Fbook_economy%20(1).jpg?alt=media&token=66d40a49-7e91-4c76-a150-f85a90720116
', 'Kuphal-Hickle', 'Jonathon Marquot', 'Wilek Benge', 'Hagenes and Sons', 2012, 211, '120x250', 149, 'Bìa Mềm', '914000', 109, 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero.', 2,0);
insert into books (id, name, image, supplier, author, translator, publisher, publish_year, weight, demension, pages, cover, price, stock, details, book_type, is_delete) values (2, 'Cách mạng màu cam ', 'https://firebasestorage.googleapis.com/v0/b/sprint-2-data.appspot.com/o/sach_kinh_te%2Fbook_economy%20(2).jpg?alt=media&token=217480a1-00b1-4ee1-ade5-855790f45c7a
', 'Douglas LLC', 'Tobiah Youd', 'Robenia Bagger', 'Hessel and Sons', 1994, 361, '150x300', 271, 'Bìa Cứng', '178000', 41, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 4,0);
insert into books (id, name, image, supplier, author, translator, publisher, publish_year, weight, demension, pages, cover, price, stock, details, book_type, is_delete ) values (3, 'Nước Mỹ dưới thời Donal Trump', 'https://firebasestorage.googleapis.com/v0/b/sprint-2-data.appspot.com/o/sach_kinh_te%2Fbook_economy%20(3).jpg?alt=media&token=2e7b1044-5285-4286-823c-161beec4cee2
', 'Weber and Sons', 'Dannie Elia', 'Thatch Wilshaw', 'Predovic Group', 2008, 364, '150x300', 279, 'Bìa Cứng', '464000', 86, 'Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 2,0);
insert into books (id, name, image, supplier, author, translator, publisher, publish_year, weight, demension, pages, cover, price, stock, details, book_type, is_delete) values (4, 'Quán tươi cười là nơi khách đến ', 'https://firebasestorage.googleapis.com/v0/b/sprint-2-data.appspot.com/o/sach_kinh_te%2Fbook_economy%20(4).jpg?alt=media&token=a96d6959-bd5d-488b-8ea2-62ac40c75ed5
', 'Olson-Block', 'Liesa Geer', 'Lishe Carmichael', 'Harvey LLC', 2000, 444, '120x250', 242, 'Bìa Cứng', '751000', 92, 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo.', 2,0);
insert into books (id, name, image, supplier, author, translator, publisher, publish_year, weight, demension, pages, cover, price, stock, details, book_type, is_delete) values (5, 'Mười sai làm chết người trong tiếp thị ', 'https://firebasestorage.googleapis.com/v0/b/sprint-2-data.appspot.com/o/sach_kinh_te%2Fbook_economy%20(5).jpg?alt=media&token=7043a916-be4e-4db5-9311-7d5a7e1473ee
', 'Rowe and Sons', 'Risa Turpin', 'Galvin De Carolis', 'Dibbert-Crooks', 1993, 341, '200x500', 117, 'Bìa Mềm', '243000', 113, 'Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum.', 3,0);
insert into books (id, name, image, supplier, author, translator, publisher, publish_year, weight, demension, pages, cover, price, stock, details, book_type, is_delete) values (6, 'Nâng tâm dịch vụ ', 'https://firebasestorage.googleapis.com/v0/b/sprint-2-data.appspot.com/o/sach_kinh_te%2Fbook_economy%20(6).jpg?alt=media&token=3e88d25e-4a5e-4fb2-84c0-923d8564c764
', 'Parker-Runolfsdottir', 'Wynn Chaster', 'Fayth Lydford', 'Mann and Sons', 2012, 358, '120x250', 114, 'Bìa Cứng', '219000', 69, 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.', 2,0);
insert into books (id, name, image, supplier, author, translator, publisher, publish_year, weight, demension, pages, cover, price, stock, details, book_type, is_delete) values (7, 'Quảng trường và tòa tháp', 'https://firebasestorage.googleapis.com/v0/b/sprint-2-data.appspot.com/o/sach_kinh_te%2Fbook_economy%20(7).jpg?alt=media&token=1527686c-3b72-4487-8211-2203e08b3eda
', 'Towne-Kris', 'Gertrudis Gurnell', 'Meagan Martyns', 'Beahan-Reichel', 2013, 393, '120x250', 233, 'Bìa Mềm', '388000', 59, 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 2,0);
insert into books (id, name, image, supplier, author, translator, publisher, publish_year, weight, demension, pages, cover, price, stock, details, book_type, is_delete) values (8, 'Jack Ma và Alibaba', 'https://firebasestorage.googleapis.com/v0/b/sprint-2-data.appspot.com/o/sach_kinh_te%2Fbook_economy%20(8).jpg?alt=media&token=a45896be-7bd7-4933-a651-0633be69f1c9
', 'Reinger-Hauck', 'Sara Tomicki', 'Guglielmo Warwick', 'Conn and Sons', 2005, 345, '120x250', 240, 'Bìa Cứng', '194000', 30, 'Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.', 1,0);
insert into books (id, name, image, supplier, author, translator, publisher, publish_year, weight, demension, pages, cover, price, stock, details, book_type, is_delete) values (9, 'Bí quyết trở thành tỉ phú', 'https://firebasestorage.googleapis.com/v0/b/sprint-2-data.appspot.com/o/sach_kinh_te%2Fbook_economy%20(9).jpg?alt=media&token=a8d4a46f-6d24-4144-8064-e7bfb314df00
', 'Bergstrom-Hauck', 'Rheba Allitt', 'Stuart Guilayn', 'Shields-Donnelly', 2000, 351, '200x500', 233, 'Bìa Cứng', '724000', 51, 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 3,0);
insert into books (id, name, image, supplier, author, translator, publisher, publish_year, weight, demension, pages, cover, price, stock, details, book_type, is_delete) values (10, 'Sói già phố wall', 'https://firebasestorage.googleapis.com/v0/b/sprint-2-data.appspot.com/o/sach_kinh_te%2Fbook_economy%20(10).jpg?alt=media&token=45019aca-8c65-4cca-b0d2-0ab97694a371
', 'Wehner, Jones and Legros', 'Ellery Mepham', 'Hayward Isley', 'Strosin-Grady', 1999, 408, '150x300', 281, 'Bìa Mềm', '325000', 69, 'Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 2,0);
insert into books (id, name, image, supplier, author, translator, publisher, publish_year, weight, demension, pages, cover, price, stock, details, book_type, is_delete) values (11, 'Định hình cuộc cách mạng công nghiệp lần thứ 4', 'https://firebasestorage.googleapis.com/v0/b/sprint-2-data.appspot.com/o/sach_kinh_te%2Fbook_economy%20(11).jpg?alt=media&token=06a0be1d-3a8d-47f1-899f-2b8dd20592b2
', 'Paucek Group', 'Patrica Vannuccini', 'Mollie Helliker', 'Pfeffer, Predovic and Lynch', 2018, 330, '120x250', 123, 'Bìa Mềm', '160000', 49, 'Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.', 1,0);
insert into books (id, name, image, supplier, author, translator, publisher, publish_year, weight, demension, pages, cover, price, stock, details, book_type, is_delete) values (12, 'Quảng cáo không nói láo', 'https://firebasestorage.googleapis.com/v0/b/sprint-2-data.appspot.com/o/sach_kinh_te%2Fbook_economy%20(12).jpg?alt=media&token=74aa797e-c47b-44d7-b37f-d574a33d4d6f
', 'Towne-Graham', 'Karmen O'' Timony', 'Becka Scalera', 'Huels-Daniel', 2006, 424, '120x250', 192, 'Bìa Mềm', '838000', 114, 'Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 2,0);
insert into books (id, name, image, supplier, author, translator, publisher, publish_year, weight, demension, pages, cover, price, stock, details, book_type, is_delete) values (13, 'Yêu trong tỉnh thức', 'https://firebasestorage.googleapis.com/v0/b/sprint-2-data.appspot.com/o/sach_tam_ly%2Fbook_tamly%20(1).jpg?alt=media&token=7438639f-f6d2-4cba-be95-dc05a1189301
', 'Mitchell-Murray', 'Anjanette Balas', 'Cherida Statefield', 'Brown and Sons', 2001, 237, '150x300', 226, 'Bìa Cứng', '864000', 90, 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.', 1,0);
insert into books (id, name, image, supplier, author, translator, publisher, publish_year, weight, demension, pages, cover, price, stock, details, book_type, is_delete) values (14, 'Tâm lý học tội phạm (Phác thảo chân dung kẻ phạm tội)', 'https://firebasestorage.googleapis.com/v0/b/sprint-2-data.appspot.com/o/sach_tam_ly%2Fbook_tamly%20(2).jpg?alt=media&token=c013dbdf-fe24-4e66-98fc-bd2d1cd00fe5
', 'Kohler, McClure and Veum', 'Harrietta Andras', 'Emmott Ashpole', 'Gutmann, Denesik and Walsh', 2011, 387, '120x250', 161, 'Bìa Cứng', '865000', 112, 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', 1,0);
insert into books (id, name, image, supplier, author, translator, publisher, publish_year, weight, demension, pages, cover, price, stock, details, book_type, is_delete) values (15, 'Thao túng tâm lý', 'https://firebasestorage.googleapis.com/v0/b/sprint-2-data.appspot.com/o/sach_tam_ly%2Fbook_tamly%20(3).jpg?alt=media&token=d4288486-e2cb-4093-bbc7-ca5f2db24420
', 'Nikolaus, Kiehn and Gaylord', 'Sylvan Pennock', 'Filmore Marginson', 'Wilderman and Sons', 2001, 374, '120x250', 162, 'Bìa Mềm', '146000', 55, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 1,0);
insert into books (id, name, image, supplier, author, translator, publisher, publish_year, weight, demension, pages, cover, price, stock, details, book_type, is_delete) values (16, 'Tâm lý học về tiền', 'https://firebasestorage.googleapis.com/v0/b/sprint-2-data.appspot.com/o/sach_tam_ly%2Fbook_tamly%20(4).jpg?alt=media&token=60e0897b-7b7d-4739-b240-61eaf190d410
', 'Moen and Sons', 'Magdalena Hastwell', 'Rafaellle Aartsen', 'Ratke LLC', 2012, 205, '150x300', 219, 'Bìa Cứng', '839000', 102, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.', 2,0);
insert into books (id, name, image, supplier, author, translator, publisher, publish_year, weight, demension, pages, cover, price, stock, details, book_type, is_delete) values (17, 'Hiểu về trái tim ', 'https://firebasestorage.googleapis.com/v0/b/sprint-2-data.appspot.com/o/sach_tam_ly%2Fbook_tamly%20(5).jpg?alt=media&token=5a4c804d-b497-4446-8fcc-65654490a6ec
', 'White Group', 'Kesley Cornu', 'Prince Bosnell', 'Prosacco-Zemlak', 2007, 263, '120x250', 128, 'Bìa Mềm', '642000', 71, 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 3,0);
insert into books (id, name, image, supplier, author, translator, publisher, publish_year, weight, demension, pages, cover, price, stock, details, book_type, is_delete) values (18, 'Thiên tài bên trái, kẻ điên bên phải', 'https://firebasestorage.googleapis.com/v0/b/sprint-2-data.appspot.com/o/sach_tam_ly%2Fbook_tamly%20(6).jpg?alt=media&token=ef41c80f-4a39-4e33-9a09-ca741baa52d1
', 'Keebler, Herzog and Stracke', 'Marcelo Ghio', 'Rolph Hardes', 'Hilpert Group', 2020, 232, '120x250', 221, 'Bìa Mềm', '662000', 102, 'In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit.', 3,0);
insert into books (id, name, image, supplier, author, translator, publisher, publish_year, weight, demension, pages, cover, price, stock, details, book_type, is_delete) values (19, 'Thay đổi cuộc sống với thần số học', 'https://firebasestorage.googleapis.com/v0/b/sprint-2-data.appspot.com/o/sach_tam_ly%2Fbook_tamly%20(7).jpg?alt=media&token=de238f56-1ade-4b65-97a4-90bdb6de1b48
', 'Lang LLC', 'Sherline Wiggam', 'Lorita McCarrison', 'Tromp, Keeling and Ledner', 2019, 234, '200x500', 245, 'Bìa Mềm', '128000', 92, 'In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh.', 2,0);
insert into books (id, name, image, supplier, author, translator, publisher, publish_year, weight, demension, pages, cover, price, stock, details, book_type, is_delete) values (20, 'Tâm lý học tinh cách ', 'https://firebasestorage.googleapis.com/v0/b/sprint-2-data.appspot.com/o/sach_tam_ly%2Fbook_tamly%20(8).jpg?alt=media&token=2143bcbf-ee6e-42f5-b9b1-5171c5e1f95b
', 'Ullrich LLC', 'Addie Kesteven', 'Quincey Fear', 'Beahan Group', 2016, 318, '120x250', 104, 'Bìa Mềm', '873000', 73, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 1,0);
insert into books (id, name, image, supplier, author, translator, publisher, publish_year, weight, demension, pages, cover, price, stock, details, book_type, is_delete) values (21, 'Chủ nghĩa khắc kỷ', 'https://firebasestorage.googleapis.com/v0/b/sprint-2-data.appspot.com/o/sach_tam_ly%2Fbook_tamly%20(9).jpg?alt=media&token=9df59ada-79d6-4165-a5ea-06e189dbaf82
', 'Doyle-Stiedemann', 'Oliy Sweeting', 'Haskell Moulder', 'Dibbert and Sons', 1992, 465, '120x250', 106, 'Bìa Cứng', '900000', 100, 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis.', 1,0);
insert into books (id, name, image, supplier, author, translator, publisher, publish_year, weight, demension, pages, cover, price, stock, details, book_type, is_delete) values (22, 'Đắc nhân tâm', 'https://firebasestorage.googleapis.com/v0/b/sprint-2-data.appspot.com/o/sach_tam_ly%2Fbook_tamly%20(10).jpg?alt=media&token=75422853-1665-42c8-949c-82f15c661fd1
', 'Heidenreich-Hegmann', 'Irene Dammarell', 'Cyndie Pudsall', 'Schultz, Adams and Schmitt', 2013, 482, '200x500', 133, 'Bìa Mềm', '214000', 87, 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 1,0);
insert into books (id, name, image, supplier, author, translator, publisher, publish_year, weight, demension, pages, cover, price, stock, details, book_type, is_delete) values (23, 'Điệp viên hoàn hảo', 'https://firebasestorage.googleapis.com/v0/b/sprint-2-data.appspot.com/o/sach_hoi_ky%2Fbook_hoiky%20(1).jpg?alt=media&token=3f598890-94f9-485c-8742-8ee4151b89dc
', 'Heathcote-Bode', 'Lee Toohey', 'Cathlene Flather', 'Gorczany, Graham and Balistreri', 2000, 371, '120x250', 154, 'Bìa Cứng', '140000', 115, 'Fusce consequat. Nulla nisl. Nunc nisl.', 1,0);
insert into books (id, name, image, supplier, author, translator, publisher, publish_year, weight, demension, pages, cover, price, stock, details, book_type, is_delete) values (24, 'Tình yêu gia đình sự nghiệp', 'https://firebasestorage.googleapis.com/v0/b/sprint-2-data.appspot.com/o/sach_hoi_ky%2Fbook_hoiky%20(2).jpg?alt=media&token=faabc949-6e29-4938-95ff-355e5ca404c2
', 'Ortiz-Littel', 'Giulio Ledgerton', 'Bartolemo Cracoe', 'Beer-Collins', 2008, 391, '150x300', 208, 'Bìa Cứng', '164000', 38, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 4,0);
insert into books (id, name, image, supplier, author, translator, publisher, publish_year, weight, demension, pages, cover, price, stock, details, book_type, is_delete) values (25, 'Không gục ngã', 'https://firebasestorage.googleapis.com/v0/b/sprint-2-data.appspot.com/o/sach_hoi_ky%2Fbook_hoiky%20(3).jpg?alt=media&token=a859b106-fda9-4409-886d-38c40ab95583
', 'Kling Inc', 'Rhiamon Daynter', 'Ariana Tytcomb', 'O''Keefe and Sons', 2021, 264, '120x250', 264, 'Bìa Mềm', '187000', 43, 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum.', 4,0);
insert into books (id, name, image, supplier, author, translator, publisher, publish_year, weight, demension, pages, cover, price, stock, details, book_type, is_delete) values (26, 'Ngọn lửa xanh', 'https://firebasestorage.googleapis.com/v0/b/sprint-2-data.appspot.com/o/sach_hoi_ky%2Fbook_hoiky%20(4).jpg?alt=media&token=812f0c0f-2fa8-4606-a32c-7c1e93d8fd53
', 'Murray-Ankunding', 'Stavro Major', 'Rochester Willacot', 'Dooley and Sons', 2015, 388, '120x250', 261, 'Bìa Cứng', '477000', 109, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 2,0);
insert into books (id, name, image, supplier, author, translator, publisher, publish_year, weight, demension, pages, cover, price, stock, details, book_type, is_delete) values (27, 'Hồi ký Trần Quốc Hưng', 'https://firebasestorage.googleapis.com/v0/b/sprint-2-data.appspot.com/o/sach_hoi_ky%2Fbook_hoiky%20(5).jpg?alt=media&token=55b1c735-b343-4775-b36f-8df69c5fc4eb
', 'Reichert, Rolfson and Aufderhar', 'Luigi Aizikov', 'Ogdon Falcus', 'Stehr and Sons', 2009, 238, '120x250', 116, 'Bìa Cứng', '223000', 53, 'Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 3,0);
insert into books (id, name, image, supplier, author, translator, publisher, publish_year, weight, demension, pages, cover, price, stock, details, book_type, is_delete) values (28, 'Khi hơi thở hóa thinh không', 'https://firebasestorage.googleapis.com/v0/b/sprint-2-data.appspot.com/o/sach_hoi_ky%2Fbook_hoiky%20(6).jpg?alt=media&token=bdb27a94-778d-47ca-bc77-9a7734ff048b
', 'Fahey Group', 'Lev Tumayan', 'Denyse Howen', 'Frami and Sons', 1998, 468, '200x500', 296, 'Bìa Mềm', '736000', 116, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 4,0);
insert into books (id, name, image, supplier, author, translator, publisher, publish_year, weight, demension, pages, cover, price, stock, details, book_type, is_delete) values (29, 'Từ kiến trúc sư thành bác sỹ ở Hoa kỳ ', 'https://firebasestorage.googleapis.com/v0/b/sprint-2-data.appspot.com/o/sach_hoi_ky%2Fbook_hoiky%20(7).jpg?alt=media&token=a579ada4-f1ce-4a4f-aa73-b2382e88b5ab
', 'Murazik Inc', 'Jess Parr', 'Zuzana Extence', 'Beier and Sons', 2013, 309, '200x500', 104, 'Bìa Mềm', '608000', 40, 'Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.', 2,0);
insert into books (id, name, image, supplier, author, translator, publisher, publish_year, weight, demension, pages, cover, price, stock, details, book_type, is_delete) values (30, 'Hồi ký Anna Frank ', 'https://firebasestorage.googleapis.com/v0/b/sprint-2-data.appspot.com/o/sach_hoi_ky%2Fbook_hoiky%20(8).jpg?alt=media&token=8675c753-96ec-4a29-a484-d12c799602f1
', 'Lubowitz-Stiedemann', 'Belinda Le Strange', 'Gerrilee Spelling', 'Goodwin Inc', 2014, 414, '120x250', 178, 'Bìa Mềm', '401000', 35, 'Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 2,0);
insert into books (id, name, image, supplier, author, translator, publisher, publish_year, weight, demension, pages, cover, price, stock, details, book_type, is_delete) values (31, 'Chạy bộ để vượt qua', 'https://firebasestorage.googleapis.com/v0/b/sprint-2-data.appspot.com/o/sach_hoi_ky%2Fbook_hoiky%20(9).jpg?alt=media&token=899a8f22-df7e-4c5b-8b06-9c2628fa9d15
', 'Waelchi and Sons', 'Dolph Baike', 'Terencio Blaxland', 'Macejkovic, Effertz and Romaguera', 2006, 453, '200x500', 247, 'Bìa Cứng', '789000', 103, 'Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', 4,0);
insert into books (id, name, image, supplier, author, translator, publisher, publish_year, weight, demension, pages, cover, price, stock, details, book_type, is_delete) values (32, 'Tôi học đại học', 'https://firebasestorage.googleapis.com/v0/b/sprint-2-data.appspot.com/o/sach_hoi_ky%2Fbook_hoiky%20(10).jpg?alt=media&token=177d2da3-dd36-44c6-aea7-8190ef08266c
', 'Rowe, Beier and Hudson', 'Kata de Chastelain', 'Julina Fincher', 'Aufderhar LLC', 1992, 404, '120x250', 279, 'Bìa Mềm', '415000', 80, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 2,0);
insert into books (id, name, image, supplier, author, translator, publisher, publish_year, weight, demension, pages, cover, price, stock, details, book_type, is_delete) values (33, 'Lý Quang Diệu nhưng điều tôi biết', 'https://firebasestorage.googleapis.com/v0/b/sprint-2-data.appspot.com/o/sach_hoi_ky%2Fbook_hoiky%20(11).jpg?alt=media&token=a3de38eb-8160-40d7-9b36-4cc636a1aafd
', 'Cummings-Halvorson', 'Nevin Royan', 'Jandy Syddall', 'Metz LLC', 1997, 340, '150x300', 109, 'Bìa Mềm', '175000', 64, 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 1,0);
insert into books (id, name, image, supplier, author, translator, publisher, publish_year, weight, demension, pages, cover, price, stock, details, book_type, is_delete) values (34, 'Elon Musk', 'https://firebasestorage.googleapis.com/v0/b/sprint-2-data.appspot.com/o/sach_hoi_ky%2Fbook_hoiky%20(12).jpg?alt=media&token=49a8659b-83b0-49fe-baf1-e2b232414525
', 'Monahan Inc', 'Towny Dils', 'Aldridge Klyn', 'Marks Inc', 1998, 500, '120x250', 201, 'Bìa Cứng', '682000', 45, 'In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna.', 3,0);
insert into books (id, name, image, supplier, author, translator, publisher, publish_year, weight, demension, pages, cover, price, stock, details, book_type, is_delete) values (35, 'Số nhọ không đọ lạc quan', 'https://firebasestorage.googleapis.com/v0/b/sprint-2-data.appspot.com/o/sach_hoi_ky%2Fbook_hoiky%20(13).jpg?alt=media&token=421475dc-63a2-44b8-9b37-85de655819d0
', 'Heathcote Group', 'Welbie Linebarger', 'Desiri Grosvener', 'Rath, Predovic and Raynor', 2010, 285, '150x300', 122, 'Bìa Mềm', '941000', 94, 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 1,0);
insert into books (id, name, image, supplier, author, translator, publisher, publish_year, weight, demension, pages, cover, price, stock, details, book_type, is_delete) values (36, 'Nhà giả kim', 'https://firebasestorage.googleapis.com/v0/b/sprint-2-data.appspot.com/o/sach_van_hoc%2Fimage_vanhoc%20(1).jpg?alt=media&token=88986b34-ad11-457a-9260-eaf70a2edc37
', 'Becker, Goodwin and Toy', 'Elsworth Heskey', 'Allister Dorling', 'Trantow Inc', 2017, 476, '200x500', 155, 'Bìa Cứng', '139000', 84, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst.', 2,0);
insert into books (id, name, image, supplier, author, translator, publisher, publish_year, weight, demension, pages, cover, price, stock, details, book_type, is_delete) values (37, 'Số đỏ', 'https://firebasestorage.googleapis.com/v0/b/sprint-2-data.appspot.com/o/sach_van_hoc%2Fimage_vanhoc%20(2).jpg?alt=media&token=9684d78c-d0af-40a0-9298-b526abd7e422
', 'McGlynn-Carroll', 'Sergio Dufer', 'Kelley Ready', 'Mohr, Gibson and Spencer', 2014, 200, '150x300', 231, 'Bìa Cứng', '302000', 91, 'Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 3,0);
insert into books (id, name, image, supplier, author, translator, publisher, publish_year, weight, demension, pages, cover, price, stock, details, book_type, is_delete) values (38, 'Dấu chân trên cát', 'https://firebasestorage.googleapis.com/v0/b/sprint-2-data.appspot.com/o/sach_van_hoc%2Fimage_vanhoc%20(3).jpg?alt=media&token=fa3d0565-19ed-470f-9d8a-508be83fd7da
', 'Feil Inc', 'Dew Dows', 'Charita Annett', 'Hartmann-King', 1998, 394, '200x500', 272, 'Bìa Cứng', '942000', 69, 'In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 4,0);
insert into books (id, name, image, supplier, author, translator, publisher, publish_year, weight, demension, pages, cover, price, stock, details, book_type, is_delete) values (39, 'Tôi thấy hoa vàng trên cỏ xanh', 'https://firebasestorage.googleapis.com/v0/b/sprint-2-data.appspot.com/o/sach_van_hoc%2Fimage_vanhoc%20(4).jpg?alt=media&token=fd411903-ca2f-492a-ad5c-d79365cf248e
', 'Rutherford, Watsica and Schaefer', 'Hank Nannini', 'Marline Bowden', 'Armstrong-Lockman', 2001, 264, '150x300', 272, 'Bìa Mềm', '295000', 104, 'Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 4,0);
insert into books (id, name, image, supplier, author, translator, publisher, publish_year, weight, demension, pages, cover, price, stock, details, book_type, is_delete) values (40, 'Giết chết chim nhạn', 'https://firebasestorage.googleapis.com/v0/b/sprint-2-data.appspot.com/o/sach_van_hoc%2Fimage_vanhoc%20(6).jpg?alt=media&token=b06d7ec0-33af-4632-a972-fbc9a103fca2
', 'Jacobs, Zulauf and Herman', 'Orran Ruske', 'Janey Vennard', 'Wiza-Ratke', 2004, 206, '150x300', 290, 'Bìa Mềm', '092000', 66, 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.', 2,0);
