insert into orders (id, customer_id, shipping_id, payment_method, date_process, is_delete, status) values (1, 16, 1, 'Paypal', '2022-01-07', 0, 0);
insert into orders (id, customer_id, shipping_id, payment_method, date_process, is_delete, status) values (2, 19, 4, 'Thanh Toán Tiền Mặt', '2022-03-02', 0, 0);
insert into orders (id, customer_id, shipping_id, payment_method, date_process, is_delete, status) values (3, 9, 2, 'Thanh Toán Tiền Mặt', '2022-12-01', 0, 0);
insert into orders (id, customer_id, shipping_id, payment_method, date_process, is_delete, status) values (4, 4, 2, 'Paypal', '2022-04-10', 0, 0);
insert into orders (id, customer_id, shipping_id, payment_method, date_process, is_delete, status) values (5, 12, 3, 'Thanh Toán Tiền Mặt', '2022-11-01', 0, 0);
insert into orders (id, customer_id, shipping_id, payment_method, date_process, is_delete, status) values (6, 3, 1, 'Thanh Toán Tiền Mặt', '2022-05-30', 0, 0);
insert into orders (id, customer_id, shipping_id, payment_method, date_process, is_delete, status) values (7, 19, 4, 'Thanh Toán Tiền Mặt', '2022-05-14', 0, 0);
insert into orders (id, customer_id, shipping_id, payment_method, date_process, is_delete, status) values (8, 7, 2, 'Paypal', '2022-07-22', 0, 0);
insert into orders (id, customer_id, shipping_id, payment_method, date_process, is_delete, status) values (9, 3, 3, 'Thanh Toán Tiền Mặt', '2022-02-23', 0, 0);
insert into orders (id, customer_id, shipping_id, payment_method, date_process, is_delete, status) values (10, 20, 3, 'Paypal', '2022-03-01', 0, 0);
insert into orders (id, customer_id, shipping_id, payment_method, date_process, is_delete, status) values (11, 13, 2, 'Paypal', '2022-06-25', 0, 0);
insert into orders (id, customer_id, shipping_id, payment_method, date_process, is_delete, status) values (12, 15, 4, 'Thanh Toán Tiền Mặt', '2021-12-26', 0, 0);
insert into orders (id, customer_id, shipping_id, payment_method, date_process, is_delete, status) values (13, 15, 4, 'Thanh Toán Tiền Mặt', '2021-12-08', 0, 0);
insert into orders (id, customer_id, shipping_id, payment_method, date_process, is_delete, status) values (14, 4, 1, 'Paypal', '2022-03-28', 0, 0);
insert into orders (id, customer_id, shipping_id, payment_method, date_process, is_delete, status) values (15, 3, 4, 'Thanh Toán Tiền Mặt', '2022-04-27', 0, 0);
insert into orders (id, customer_id, shipping_id, payment_method, date_process, is_delete, status) values (16, 12, 4, 'Paypal', '2022-10-23', 0, 0);
insert into orders (id, customer_id, shipping_id, payment_method, date_process, is_delete, status) values (17, 14, 3, 'Paypal', '2022-09-08', 0, 0);
insert into orders (id, customer_id, shipping_id, payment_method, date_process, is_delete, status) values (18, 9, 1, 'Paypal', '2022-07-21', 0, 0);
insert into orders (id, customer_id, shipping_id, payment_method, date_process, is_delete, status) values (19, 20, 1, 'Paypal', '2022-07-18', 0, 0);
insert into orders (id, customer_id, shipping_id, payment_method, date_process, is_delete, status) values (20, 19, 2, 'Paypal', '2022-08-05', 0, 0);
